### ISSUE TITLE
Support for Android and/or the Web

### ISSUE THREAD

**Issue by elihschiff** [wtg/Shuttle-Tracker-SwiftUI-2.0#2]
Many people, especially at RPI, use android devices and therefore cannot use this app. While a android app would be ideal, a web version similar to shuttle tracker would be very helpful.

Especially if you plan on crowd sourcing data, having more users is essential to getting accurate up to date shuttle locations.

**Comment by Gerzer** [comment]
I agree that an Android app would be a good idea. However, I have exactly zero experience with Android development, and I don't have any Android devices on which to test it anyway.

This leaves two options: either we settle for a Web app, which I can build myself, but which won't be as optimized or full-featured as a native app, or someone else can build an Android app.

A decent portion of the core logic is server-side, and it's exposed via a simple JSON API, so a minimum viable native Android app could just display a map with route lines, stops, and buses as overlays. Obviously, since much of the appeal of Shuttle Tracker is its crowd-sourced data, it would be great if this hypothetical Android app also supported sending real-time location data to the server. I built the current state of the iOS/iPadOS/macOS app in a little over a week, so it shouldn't take *too* long to build a comparable port for an experienced Android developer. I do plan to introduce more fancy features in the iOS/iPadOS/macOS(/watchOS) app like support for Apple Watch and NFC/QR-code App Clips, but a suitable Android app wouldn't necessarily need those features unless someone wants to spend the time building them as extras.

The other option is merely to build a simple Web app, which I could do myself. The iOS/iPadOS/macOS app uses Apple's MapKit framework for, well, the map and location features, and Apple does offer a Web version of it, MapKit JS. I haven't looked at its documentation thoroughly yet, so I don't know if there are any limitations that might make a Web version hard or impossible. If it turns out that MapKit JS doesn't offer the right features, then I could look into using the Google Maps APIs (and I would try to get over my personal disdain for Google and its products, Maps included). There is one major issue with a Web app that I predict, though: it would likely be hard—or even impossible—to send real-time location data to the server from the Web browser without burdening the user too much. Would it be reasonable to ask that users leave the website open and on-screen for the duration of their shuttle ride? I would think not, but maybe someone can convince me otherwise. A native Android app wouldn't have this limitation; the user could leave it in the background and do something else while the app continues to send location data to the server. (Currently, the iOS app doesn't work all that well in the background, but I know what I need to do to enable reliable background location data; I just haven't done it yet.)

Of course, the best thing would be to build both a native Android app and a Web app, but we need to be mindful of what can reasonably be built in a reasonable amount of time by people who might be willing to work on the project. Personally, I'm willing and able to build a Web app (once I've built the first release version of the iOS/iPadOS/macOS/watchOS app, that is), and I'm willing—but not currently able—to build a native Android app.

**Comment by Gerzer** [comment]
Here's an update on this: we plan to repurpose the existing, in-development Flutter app from the old Shuttle Tracker team and to modify it so that it can communicate with the new server and send and receive crowd-sourced location data. The Flutter app will become the official Android version.

Separately, we plan to investigate how much work it would take to retrofit the existing Web interface (http://shuttles.rpi.edu) to use the new crowd-sourced data. If it turns out that it's not worth the effort, then we have two options: we could build a brand-new Web interface, perhaps with MapKit JS, or we could adapt the repurposed Flutter app for the Web.
